apiVersion: apps.kubeblocks.io/v1alpha1
kind: ClusterDefinition
metadata:
  name: {{ include "victoriametrics-cdName" . }}
spec:
  topologies:
    - components:
        - compDef: {{ include "victoriametrics-insert.cmpdName" . }}
          name: insert
        - compDef: {{ include "victoriametrics-select.cmpdName" . }}
          name: select
        - compDef: {{ include "victoriametrics-storage.cmpdName" . }}
          name: storage
      default: true
      name: victoriametrics