apiVersion: apps.kubeblocks.io/v1alpha1
kind: ClusterDefinition
metadata:
  name: {{ include "victoriametrics-cdName" . }}
spec:
  topologies:
    - name: cluster
      default: true
      components:
        - name: vminsert
          compDef: {{ include "victoriametrics-insert.cmpdRegexpPattern" . }}
        - name: vmselect
          compDef: {{ include "victoriametrics-select.cmpdRegexpPattern" . }}
        - name: vmstorage
          compDef: {{ include "victoriametrics-storage.cmpdRegexpPattern" . }}
      orders:
        provision:
          - vmstorage
          - vminsert,vmselect
    - name: select
      default: false
      components:
        - compDef: {{ include "victoriametrics-select.cmpdName" . }}
          name: vmselect


