apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "vm.cmScriptsName" . }}
  namespace: {{ .Release.Namespace }}
data:
  {{- range $path, $_ :=  $.Files.Glob "scripts/**" }}
  {{ $path | base }}: |-
  {{- $.Files.Get $path | nindent 4 }}
  {{- end }}