apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "minio.config" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "minio.labels" . | nindent 4 }}
data:
  MINIO_REPLICAS_HISTORY: "[]"