apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "bkdata-kafka-consumer.fullname" . }}
  labels:
    {{- include "bkdata-kafka-consumer.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "bkdata-kafka-consumer.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        reloader.stakater.com/auto: "true"
      labels:
        {{- include "bkdata-kafka-consumer.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "bkdata-kafka-consumer.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      volumes:
        -
          name: config-volume
          configMap:
            name:  bkdata-kafka-consumer-configmap
            items:
              -
                key: config.yaml
                mode: 420
                path: path/to/config.yaml
              -
                key: data.mysql-db-table-size.yaml
                mode: 420
                path: path/to/data.mysql-db-table-size.yaml
              -
                key: data.mysql-backup-result.yaml
                mode: 420
                path: path/to/data.mysql-backup-result.yaml
              -
                key: data.mysql-binlog-result.yaml
                mode: 420
                path: path/to/data.mysql-binlog-result.yaml
            defaultMode: 272
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.global.imageRegistry | default .Values.image.registry }}/{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 7000
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            -
              name: config-volume
              subPath: path/to/config.yaml
              mountPath: /config.yaml
            -
              name: config-volume
              subPath: path/to/data.mysql-db-table-size.yaml
              mountPath: /data.mysql-db-table-size.yaml
            -
              name: config-volume
              subPath: path/to/data.mysql-backup-result.yaml
              mountPath: /data.mysql-backup-result.yaml
            -
              name: config-volume
              subPath: data.mysql-binlog-result.yaml
              mountPath: data.mysql-binlog-result.yaml
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
