report_save_dir: /home/mysql/dbareport/
report_left_day: 15
backup_client_storage_type: cos
http_address: 127.0.0.1:6677
bkmonitorbeat:
    agent_address: /usr/local/gse_bkte/agent/data/ipc.state.report
    beat_path: /usr/local/gse_bkte/plugins/bin/bkmonitorbeat
    event_config:
        data_id: 1572877
        token: xxxx
    metric_config:
        data_id: 1572876
        token: xxxx
servers:
    - bk_cloud_id: 0
      bk_biz_id: 3
      app: dba
      app_name: DBA业务
      cluster_domain: m1.test.dba.db
      cluster_id: 12345
      cluster_name: test2
      cluster_type: MongoReplicaSet
      role_type: shardsvr
      meta_role: backup
      ip: 1.1.1.8
      port: 27031
      set_name: set2
      username: xxxx
      password: xxxx

