enableTCP6: false

vmselect:
  # -- Service port
  servicePort: 8481
  # Extra command line arguments for vmselect component
  extraArgs:
    envflag.enable: "true"
    envflag.prefix: VM_
    loggerFormat: json
    search.maxUniqueTimeseries: 990000
    search.maxPointsPerTimeseries: 500000
    search.maxSeries: 200000
    search.maxConcurrentRequests: 8
    memory.allowedPercent: 50
    search.logSlowQueryDuration: 15s
    search.queryStats.lastQueriesCount: 50000
    search.queryStats.minQueryDuration: 5s
    search.maxQueryLen: 1MB
    dedup.minScrapeInterval: 1ms

vminsert:
  # -- Service port
  servicePort: 8480
  # Extra command line arguments for vmselect component
  extraArgs:
    envflag.enable: "true"
    envflag.prefix: VM_
    loggerFormat: json

vmstorage:
  # -- Service port
  servicePort: 8482
  # -- Port for accepting connections from vminsert
  vminsertPort: 8400
  # -- Port for accepting connections from vmselect
  vmselectPort: 8401
  # Extra command line arguments for vmselect component
  extraArgs:
    envflag.enable: "true"
    envflag.prefix: VM_
    loggerFormat: json
